apiVersion: v1
kind: Secret
metadata:
  name: project-secrets
  namespace: project
type: Opaque
stringData:
  mongodb-connection: "mongodb://admin:CAMBIAR@mongodb.infrastructure.svc.cluster.local:27017"
  rabbitmq-connection: "amqp://admin:CAMBIAR@rabbitmq.infrastructure.svc.cluster.local:5672"
  redis-connection: "redis.infrastructure.svc.cluster.local:6379"
  jwt-secret: "CAMBIAR_POR_TU_JWT_SECRET_DE_32_CARACTERES_MINIMO"
  sentry-dsn: "CAMBIAR_POR_TU_SENTRY_DSN"
